/**
 * This class is generated by jOOQ
 */
package cn.axboy.demo.mixdb.jooq.tables;


import cn.axboy.demo.mixdb.jooq.DefaultSchema;
import cn.axboy.demo.mixdb.jooq.Keys;
import cn.axboy.demo.mixdb.jooq.tables.records.DemoCategoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemoCategory extends TableImpl<DemoCategoryRecord> {

    private static final long serialVersionUID = 1480339033;

    /**
     * The reference instance of <code>demo_category</code>
     */
    public static final DemoCategory DEMO_CATEGORY = new DemoCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DemoCategoryRecord> getRecordType() {
        return DemoCategoryRecord.class;
    }

    /**
     * The column <code>demo_category.id</code>.
     */
    public final TableField<DemoCategoryRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>demo_category.created_by</code>.
     */
    public final TableField<DemoCategoryRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>demo_category.created_time</code>.
     */
    public final TableField<DemoCategoryRecord, Long> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo_category.flag</code>.
     */
    public final TableField<DemoCategoryRecord, Integer> FLAG = createField("flag", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>demo_category.last_modified_by</code>.
     */
    public final TableField<DemoCategoryRecord, String> LAST_MODIFIED_BY = createField("last_modified_by", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>demo_category.last_modified_time</code>.
     */
    public final TableField<DemoCategoryRecord, Long> LAST_MODIFIED_TIME = createField("last_modified_time", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>demo_category.title</code>.
     */
    public final TableField<DemoCategoryRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>demo_category</code> table reference
     */
    public DemoCategory() {
        this("demo_category", null);
    }

    /**
     * Create an aliased <code>demo_category</code> table reference
     */
    public DemoCategory(String alias) {
        this(alias, DEMO_CATEGORY);
    }

    private DemoCategory(String alias, Table<DemoCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private DemoCategory(String alias, Table<DemoCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DemoCategoryRecord, Long> getIdentity() {
        return Keys.IDENTITY_DEMO_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DemoCategoryRecord> getPrimaryKey() {
        return Keys.KEY_DEMO_CATEGORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DemoCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<DemoCategoryRecord>>asList(Keys.KEY_DEMO_CATEGORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoCategory as(String alias) {
        return new DemoCategory(alias, this);
    }

    /**
     * Rename this table
     */
    public DemoCategory rename(String name) {
        return new DemoCategory(name, null);
    }
}
