server:
  port: 8081

logging.level:
  root: warn
  cn.axboy: debug

cn.axboy:
  task:
    enable: true

xxl.job:
  admin.addresses: http://192.168.1.142:8080/xxl-job-admin
  accessToken: default_token
  executor:
    appname: xxl-job-executor-sample
    address:
    ip: 192.168.1.65
    port: 9999
    logpath: ./logs/xxl-job/jobhandler
    logretentiondays: 7