spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.2.10:3306/demo?useUnicode=true&characterEncoding=utf8
        name:
        username: demo_root
        password: 123456
    jpa:
        database: MYSQL
        show-sql: false
        hibernate.ddl-auto: update
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    jooq:
        sql-dialect: mysql
server:
    port: 8080