/**
 * This class is generated by jOOQ
 */
package cn.axboy.demo.mixdb.jooq;


import cn.axboy.demo.mixdb.jooq.tables.DemoCategory;
import cn.axboy.demo.mixdb.jooq.tables.DemoProduct;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1250398609;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>demo_category</code>.
     */
    public final DemoCategory DEMO_CATEGORY = cn.axboy.demo.mixdb.jooq.tables.DemoCategory.DEMO_CATEGORY;

    /**
     * The table <code>demo_product</code>.
     */
    public final DemoProduct DEMO_PRODUCT = cn.axboy.demo.mixdb.jooq.tables.DemoProduct.DEMO_PRODUCT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            DemoCategory.DEMO_CATEGORY,
            DemoProduct.DEMO_PRODUCT);
    }
}
