/**
 * This class is generated by jOOQ
 */
package cn.axboy.demo.mixjpajooq.jooq.tables.records;


import cn.axboy.demo.mixjpajooq.jooq.tables.DemoProduct;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemoProductRecord extends UpdatableRecordImpl<DemoProductRecord> implements Record9<Long, String, Long, Integer, String, Long, Integer, String, Long> {

    private static final long serialVersionUID = -331636632;

    /**
     * Setter for <code>demo_product.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>demo_product.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>demo_product.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demo_product.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>demo_product.created_time</code>.
     */
    public void setCreatedTime(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>demo_product.created_time</code>.
     */
    public Long getCreatedTime() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>demo_product.flag</code>.
     */
    public void setFlag(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>demo_product.flag</code>.
     */
    public Integer getFlag() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>demo_product.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>demo_product.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>demo_product.last_modified_time</code>.
     */
    public void setLastModifiedTime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>demo_product.last_modified_time</code>.
     */
    public Long getLastModifiedTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>demo_product.inventory</code>.
     */
    public void setInventory(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>demo_product.inventory</code>.
     */
    public Integer getInventory() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>demo_product.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>demo_product.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>demo_product.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>demo_product.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Long, Integer, String, Long, Integer, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Long, Integer, String, Long, Integer, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DemoProduct.DEMO_PRODUCT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DemoProduct.DEMO_PRODUCT.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return DemoProduct.DEMO_PRODUCT.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DemoProduct.DEMO_PRODUCT.FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DemoProduct.DEMO_PRODUCT.LAST_MODIFIED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return DemoProduct.DEMO_PRODUCT.LAST_MODIFIED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DemoProduct.DEMO_PRODUCT.INVENTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DemoProduct.DEMO_PRODUCT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return DemoProduct.DEMO_PRODUCT.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLastModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getLastModifiedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getInventory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value3(Long value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value4(Integer value) {
        setFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value5(String value) {
        setLastModifiedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value6(Long value) {
        setLastModifiedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value7(Integer value) {
        setInventory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value8(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord value9(Long value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemoProductRecord values(Long value1, String value2, Long value3, Integer value4, String value5, Long value6, Integer value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemoProductRecord
     */
    public DemoProductRecord() {
        super(DemoProduct.DEMO_PRODUCT);
    }

    /**
     * Create a detached, initialised DemoProductRecord
     */
    public DemoProductRecord(Long id, String createdBy, Long createdTime, Integer flag, String lastModifiedBy, Long lastModifiedTime, Integer inventory, String name, Long categoryId) {
        super(DemoProduct.DEMO_PRODUCT);

        set(0, id);
        set(1, createdBy);
        set(2, createdTime);
        set(3, flag);
        set(4, lastModifiedBy);
        set(5, lastModifiedTime);
        set(6, inventory);
        set(7, name);
        set(8, categoryId);
    }
}
