/**
 * This class is generated by jOOQ
 */
package cn.axboy.demo.mixjpajooq.jooq;


import cn.axboy.demo.mixjpajooq.jooq.tables.DemoCategory;
import cn.axboy.demo.mixjpajooq.jooq.tables.DemoProduct;
import cn.axboy.demo.mixjpajooq.jooq.tables.records.DemoCategoryRecord;
import cn.axboy.demo.mixjpajooq.jooq.tables.records.DemoProductRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DemoCategoryRecord, Long> IDENTITY_DEMO_CATEGORY = Identities0.IDENTITY_DEMO_CATEGORY;
    public static final Identity<DemoProductRecord, Long> IDENTITY_DEMO_PRODUCT = Identities0.IDENTITY_DEMO_PRODUCT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DemoCategoryRecord> KEY_DEMO_CATEGORY_PRIMARY = UniqueKeys0.KEY_DEMO_CATEGORY_PRIMARY;
    public static final UniqueKey<DemoProductRecord> KEY_DEMO_PRODUCT_PRIMARY = UniqueKeys0.KEY_DEMO_PRODUCT_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DemoProductRecord, DemoCategoryRecord> FKG2SQBVFN8C7MH2COX229TIS6 = ForeignKeys0.FKG2SQBVFN8C7MH2COX229TIS6;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<DemoCategoryRecord, Long> IDENTITY_DEMO_CATEGORY = createIdentity(DemoCategory.DEMO_CATEGORY, DemoCategory.DEMO_CATEGORY.ID);
        public static Identity<DemoProductRecord, Long> IDENTITY_DEMO_PRODUCT = createIdentity(DemoProduct.DEMO_PRODUCT, DemoProduct.DEMO_PRODUCT.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DemoCategoryRecord> KEY_DEMO_CATEGORY_PRIMARY = createUniqueKey(DemoCategory.DEMO_CATEGORY, "KEY_demo_category_PRIMARY", DemoCategory.DEMO_CATEGORY.ID);
        public static final UniqueKey<DemoProductRecord> KEY_DEMO_PRODUCT_PRIMARY = createUniqueKey(DemoProduct.DEMO_PRODUCT, "KEY_demo_product_PRIMARY", DemoProduct.DEMO_PRODUCT.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<DemoProductRecord, DemoCategoryRecord> FKG2SQBVFN8C7MH2COX229TIS6 = createForeignKey(cn.axboy.demo.mixjpajooq.jooq.Keys.KEY_DEMO_CATEGORY_PRIMARY, DemoProduct.DEMO_PRODUCT, "FKg2sqbvfn8c7mh2cox229tis6", DemoProduct.DEMO_PRODUCT.CATEGORY_ID);
    }
}
