/**
 * This class is generated by jOOQ
 */
package cn.axboy.demo.mixjpajooq.jooq;


import cn.axboy.demo.mixjpajooq.jooq.tables.DemoCategory;
import cn.axboy.demo.mixjpajooq.jooq.tables.DemoProduct;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demo_category</code>.
     */
    public static final DemoCategory DEMO_CATEGORY = cn.axboy.demo.mixjpajooq.jooq.tables.DemoCategory.DEMO_CATEGORY;

    /**
     * The table <code>demo_product</code>.
     */
    public static final DemoProduct DEMO_PRODUCT = cn.axboy.demo.mixjpajooq.jooq.tables.DemoProduct.DEMO_PRODUCT;
}
